### ISSUE TITLE
Chrome Options - Window Size Option

### ISSUE THREAD

**Issue by viper3400** [serenity-js/serenity-js-mocha-webdriverio-template#2]
https://github.com/serenity-js/serenity-js-mocha-webdriverio-template/blob/89ea40bb1cce80e8e2fd941538415a04d90b2026/wdio.conf.ts#L64

@jan-molak: I think, this has to be a comma instead of a ```x```:

```"--window-size=1920,1080"```

Otherwise it seems to fall back to the default size.

**Comment by jan-molak** [comment]
Thanks, let me check

**Comment by jan-molak** [comment]
Yup, nice catch. Thanks!
